name: MCScreenshare
version: ${project.version}
main: mc.screenshare.Main
api-version: 1.13
authors: [MorganAnkan, BlueBurgersTDD]
description: share your screen in minecraft
commands:
  draw:
    usage: /draw
    description: Start the screenshare
