name: MCScreenshare
version: ${project.version}
main: mc.screenshare.MCScreenshare
api-version: 1.13
authors: [MorganAnkan, TheBlueBurger]
description: Screenshare but it displays in minecraft.
website: https://blueburgerstdd.github.io/mcscreenshare/
commands:
  draw:
    usage: /draw
    description: Start the screenshare
    permission: mcscreenshare.sceenshare.start
    aliases:
      - screenshare
      - start
